server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/helowin
    username: CHAT
    password: CHAT
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource